AWSTemplateFormatVersion: 2010-09-09
Description: A Lambda function (and associated resources) which takes election data which has been written to an S3 bucket and dispatches it to the mobile notifications system (n10n).
Parameters:
  Stack:
    Description: Stack name
    Type: String
  App:
    Description: Application name
    Type: String
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - CODE
      - PROD
  AlarmTopic:
    Type: String
    Description: The ARN of the SNS topic to send all the cloudwatch alarms to

Mappings:
  StageVariables:
    CODE:
      AlarmActionsEnabled: FALSE
      ScheduleStatus: ENABLED
      NotificationsApiKeyPath: "/notifications/CODE/mobile-notifications/notifications.api.secretKeys.2"
      NotificationsEndpoint: "notification.notifications.code.dev-guardianapis.com"
      ElectionsDataDirectory: "2020/11/us-general-election-data/max/"
      SendingEnabled: "true"
    PROD:
      AlarmActionsEnabled: TRUE
      ScheduleStatus: ENABLED
      NotificationsApiKeyPath: "/notifications/PROD/mobile-notifications/notifications.api.secretKeys.4"
      NotificationsEndpoint: "notification.notifications.guardianapis.com"
      ElectionsDataDirectory: "2020/11/us-general-election-data/prod/"
      SendingEnabled: "false"

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: logs
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - cloudwatch:putMetricData
              Resource: "*"
        - PolicyName: s3
          PolicyDocument:
            Statement:
              - Action:
                  - s3:GetObject
                Effect: Allow
                Resource: !Sub
                  - arn:aws:s3:::gdn-cdn/${DataDirectory}*
                  - DataDirectory: !FindInMap [StageVariables, !Ref Stage, ElectionsDataDirectory]
              - Action:  s3:ListBucket
                Effect: Allow
                Resource: arn:aws:s3:::gdn-cdn
        - PolicyName: ssm
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: !Sub
                - arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${Path}
                - Path: !FindInMap [StageVariables, !Ref Stage, NotificationsApiKeyPath]

  Function:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: mobile-dist
        S3Key: !Sub ${Stack}/${Stage}/notification-lambda/notification-lambda.zip
      Description: Dispatch notification data from an S3 bucket to the mobile notification system.
      Environment:
        Variables:
          Stage: !Ref Stage
          Stack: !Ref Stack
          App: !Ref App
          NotificationsApiKeyPath: !FindInMap [StageVariables, !Ref Stage, NotificationsApiKeyPath]
          SendingEnabled: !FindInMap [StageVariables, !Ref Stage, SendingEnabled]
          NotificationsEndpoint: !FindInMap [StageVariables, !Ref Stage, NotificationsEndpoint]
          ElectionsDataDirectory: !FindInMap [StageVariables, !Ref Stage, ElectionsDataDirectory]
      FunctionName: !Sub us-election-2020-notification-lambda-${Stage}
      Handler: notification-lambda.handler
      MemorySize: 384
      ReservedConcurrentExecutions: 1
      Role: !GetAtt Role.Arn
      Runtime: nodejs12.x
      Timeout: 300
      Tags:
        - Key: Stage
          Value: !Ref Stage
        - Key: Stack
          Value: !Ref Stack
        - Key: App
          Value: !Ref App

  EventRule:
    Type: AWS::Events::Rule
    Properties:
      State: !FindInMap [StageVariables, !Ref Stage, ScheduleStatus]
      ScheduleExpression: rate(2 minutes)
      Targets:
        - Id: !Sub NotificationLambda${Stage}Target
          Arn: !GetAtt Function.Arn

  EventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt Function.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt EventRule.Arn

  LambdaAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: !FindInMap [StageVariables, !Ref Stage, AlarmActionsEnabled]
      AlarmActions: [!Ref AlarmTopic]
      OKActions: [!Ref AlarmTopic]
      AlarmDescription: !Sub Alarm triggers if there is missing notification data, see runbook <<<Runbook|https://docs.google.com/document/d/1JQXFacHrAFB8_7fLthUkIdt1LPYTD99PxJOU_64rY2Y/edit?usp=sharing>>>
      Metrics:
        - Id: e1
          Label: Error percentage of lambda
          Expression: "100*(m1/m2)"
        - Id: m1
          Label: Number of errors for lambda
          MetricStat:
            Metric:
              MetricName: Errors
              Namespace: AWS/Lambda
              Dimensions:
                - Name: FunctionName
                  Value: !Sub us-election-2020-notification-lambda-${Stage}
            Period: 600
            Stat: Sum
          ReturnData: false
        - Id: m2
          Label: Number of invocations for lambda
          MetricStat:
            Metric:
              MetricName: Invocations
              Namespace: AWS/Lambda
              Dimensions:
                - Name: FunctionName
                  Value: !Sub us-election-2020-notification-lambda-${Stage}
            Period: 600
            Stat: Sum
          ReturnData: false
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      Threshold: 100
      TreatMissingData: notBreaching
